import { AlertCircle, ArrowLeft, Bell, ChevronRight, CircleDollarSign, Clock3, LogOut, Menu, Search, X } from "lucide-react";
import { Link, NavLink, useLocation, useNavigate } from "react-router-dom";
import { useState } from "react";
import { useAuth } from "./auth";
import { initials, titleCase } from "./lib";

export function Badge({ value, kind }: { value: string; kind?: "status" | "intent" }) {
  const normalized = value.toUpperCase();
  const tones: Record<string, string> = { PAID: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", SUCCEEDED: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", COMPLETED: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", OPEN: "bg-sky-50 text-sky-700 ring-sky-600/20", PROCESSING: "bg-sky-50 text-sky-700 ring-sky-600/20", PENDING: "bg-amber-50 text-amber-800 ring-amber-600/20", PARTIALLY_PAID: "bg-violet-50 text-violet-700 ring-violet-600/20", OVERDUE: "bg-rose-50 text-rose-700 ring-rose-600/20", FAILED: "bg-rose-50 text-rose-700 ring-rose-600/20", CANCELLED: "bg-slate-100 text-slate-600 ring-slate-500/20", DISPUTE: "bg-rose-50 text-rose-700 ring-rose-600/20", PAYMENT_CONFIRMED: "bg-brand-50 text-brand-700 ring-brand-600/20", PAYMENT_PROMISED: "bg-brand-50 text-brand-700 ring-brand-600/20" };
  const tone = tones[normalized] || (kind === "intent" ? "bg-brand-50 text-brand-700 ring-brand-600/20" : "bg-slate-100 text-slate-700 ring-slate-500/20");
  return <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset ${tone}`}>{titleCase(value)}</span>;
}

export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="panel flex min-h-56 flex-col items-center justify-center px-6 text-center"><AlertCircle className="mb-3 h-8 w-8 text-rose-600"/><h2 className="text-base font-semibold">Something needs attention</h2><p className="mt-1 max-w-md text-sm text-muted">{message}</p>{retry && <button className="btn-secondary mt-5" onClick={retry}>Try again</button>}</div>; }
export function EmptyState({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="panel flex min-h-56 flex-col items-center justify-center px-6 text-center"><CircleDollarSign className="mb-3 h-8 w-8 text-slate-300"/><h2 className="text-base font-semibold">{title}</h2><p className="mt-1 max-w-md text-sm text-muted">{detail}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function TableSkeleton({ rows = 5 }: { rows?: number }) { return <div className="panel overflow-hidden"><div className="h-12 border-b bg-slate-50"/>{Array.from({ length: rows }).map((_, index) => <div className="flex gap-5 border-b px-5 py-4 last:border-0" key={index}><div className="h-4 w-1/4 animate-pulse rounded bg-slate-100"/><div className="h-4 w-1/3 animate-pulse rounded bg-slate-100"/><div className="h-4 w-1/5 animate-pulse rounded bg-slate-100"/></div>)}</div>; }
export function PageHeader({ title, detail, back }: { title: string; detail?: string; back?: string }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-3"> <div>{back && <Link to={back} className="mb-2 inline-flex items-center gap-1 text-sm text-muted hover:text-ink"><ArrowLeft className="h-4 w-4"/>Back</Link>}<h1 className="text-2xl font-semibold tracking-tight text-ink">{title}</h1>{detail && <p className="mt-1 text-sm text-muted">{detail}</p>}</div></div>; }

const nav = [
  { label: "Overview", items: [{ to: "/dashboard", label: "Dashboard", icon: CircleDollarSign }] },
  { label: "Receivables", items: [{ to: "/invoices", label: "Invoices", icon: Clock3 }, { to: "/customers", label: "Customers", icon: ChevronRight }, { to: "/conversations", label: "Conversations", icon: Bell }] },
  { label: "Collections", items: [{ to: "/collection-actions", label: "Collection actions", icon: AlertCircle }] },
];
function SidebarContent({ close }: { close?: () => void }) { const { user, logout } = useAuth(); const navigate = useNavigate(); return <><div className="flex h-16 items-center justify-between border-b px-5"><Link to="/dashboard" className="flex items-center gap-2.5" onClick={close}><span className="grid h-8 w-8 place-items-center rounded-md bg-brand-600 text-sm font-bold text-white">L</span><span className="text-base font-semibold tracking-tight">Ledgerlane</span></Link>{close && <button className="btn h-8 w-8 px-0 lg:hidden" aria-label="Close navigation" onClick={close}><X className="h-5 w-5"/></button>}</div><nav className="flex-1 overflow-y-auto px-3 py-5">{nav.map((group) => <div className="mb-6" key={group.label}><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400">{group.label}</p>{group.items.map(({ to, label, icon: Icon }) => <NavLink end to={to} onClick={close} className={({ isActive }) => `mb-1 flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-colors ${isActive ? "bg-brand-50 text-brand-700" : "text-slate-600 hover:bg-slate-50 hover:text-ink"}`} key={to}><Icon className="h-[18px] w-[18px]"/>{label}</NavLink>)}</div>)}</nav><div className="border-t p-3"><div className="mb-2 flex items-center gap-3 rounded-md px-2 py-2"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-semibold text-slate-600">{initials(user?.name || user?.email)}</span><span className="min-w-0"><span className="block truncate text-sm font-medium">{user?.name || "Account user"}</span><span className="block truncate text-xs text-muted">{user?.email}</span></span></div><button onClick={() => { logout(); navigate("/login"); }} className="flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50 hover:text-ink"><LogOut className="h-[18px] w-[18px]"/>Sign out</button></div></>; }
export function Shell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); const location = useLocation(); return <div className="min-h-screen"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r bg-white lg:flex"><SidebarContent/></aside>{open && <div className="fixed inset-0 z-40 bg-slate-950/30 lg:hidden" onClick={() => setOpen(false)}><aside className="absolute inset-y-0 left-0 flex w-72 flex-col bg-white shadow-xl" onClick={(event) => event.stopPropagation()}><SidebarContent close={() => setOpen(false)}/></aside></div>}<main className="min-h-screen lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur sm:px-7"><button aria-label="Open navigation" className="btn h-9 w-9 px-0 lg:hidden" onClick={() => setOpen(true)}><Menu className="h-5 w-5"/></button><div className="hidden text-sm text-muted sm:block">Operations <span className="mx-1 text-slate-300">/</span> <span className="font-medium text-slate-700">{location.pathname.split("/")[1].replace("-", " ") || "dashboard"}</span></div><div className="ml-auto flex items-center gap-3"><button aria-label="Notifications" className="btn h-9 w-9 px-0 text-slate-500 hover:bg-slate-50"><Bell className="h-[18px] w-[18px]"/></button><span className="hidden text-right text-xs text-muted sm:block">Collections<br/><span className="font-medium text-slate-700">Workspace</span></span></div></header><div className="mx-auto max-w-[1440px] px-4 py-7 sm:px-7">{children}</div></main></div>; }
export function SearchInput({ value, onChange, placeholder = "Search" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="relative block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="input pl-9" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} aria-label={placeholder}/></label>; }
